# K-Means

In [2]:
import numpy as np

In [56]:
# initialize data

data1 = np.array([[1,2],[1,3],[1,5],[2,3],[2,1],[6,7],[5,6],[5,9],[7,6],[8,6]])

print(data1)

[[1 2]
 [1 3]
 [1 5]
 [2 3]
 [2 1]
 [6 7]
 [5 6]
 [5 9]
 [7 6]
 [8 6]]


In [ ]:
# kmeans(data, k)
# input: data = [[1,2]]
#        k = 1
# output: 
#
def kmeans(data, k):
    # Initialization
    centers = np.zeros((2,k))
    new_centers = np.zeros((2,k))

#    for i in range(0,k):
#        centers[i] = data[np.random.randint(0,data.shape[0])]
#    print("Centers:\n", centers)

    sample_indices = np.random.choice(data.shape[0], k, replace=False)
    centers = data[sample_indices]
    print("Centers:\n", centers)

    # Learning
    while new_centers != centers:
        # Compute Distances
        distances = np.ones((k,data.shape[0]))
        print("Distances:\n", distances)

        for x in range(0,k):
            for y in range(0,data.shape[0]):
                distance = np.linalg.norm(centers[x] - data[y])
                distances[x][y] = distance
        print("Distances:\n", distances)

        # Identify closest clusters
        centers = np.argmin(distances,axis=0)
        print("Centers:\n", centers)

        # Update centers
        for z in range(0,k):
            new_centers[z] = np.array(data[centers == z].mean(axis=0))
        print("New Centers:\n", new_centers)

    return



kmeans(data1, 2)

In [61]:
# kmeans(data, k)
# input: data = [[1,2]]
#        k = 1
# output: 
#
def kmeans(data, k):
    # Initialization
    centers = np.zeros((2,k))
    for i in range(0,k):
        centers[i] = data[np.random.randint(0,data.shape[0])]
    print(centers)

    #new_centers = np.zeros(2,k)

    # Learning
    # while new_centers != centers:
    # Compute Distances
    distances = np.ones((k,data.shape[0]))
    print(distances)

    for x in range(0,k):
        for y in range(0,data.shape[0]):
            distance = np.linalg.norm(centers[x] - data[y])
            distances[x][y] = distance
            
    print(distances)


    # Identify closest clusters
    centers = np.argmin(distances,axis=0)
    print(centers)

    # Update centers
    for z in range(0,k):
        x_mean = np.mean(data)



    return



kmeans(data1, 2)

[[5. 6.]
 [6. 7.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[5.65685425 5.         4.12310563 4.24264069 5.83095189 1.41421356
  0.         3.         2.         3.        ]
 [7.07106781 6.40312424 5.38516481 5.65685425 7.21110255 0.
  1.41421356 2.23606798 1.41421356 2.23606798]]
[0 0 0 0 0 1 0 1 1 1]
